apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-identity
  namespace: openshift-network-operator
  labels:
    {{- include "dpf-hcp-provisioner-operator.labels" . | nindent 4 }}
data:
  enabled: "false"