#!/usr/bin/env python3
"""Generates Helm RBAC templates from controller-gen output.

config/rbac/role.yaml may contain multiple YAML documents, each a Kubernetes
RBAC resource. This script writes a Helm template for each one, named after
its kind (e.g. clusterrole-manager-role.yaml, role-openshift-config-manager-role.yaml).

Requires yq on PATH for YAML processing.
"""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "config" / "rbac" / "role.yaml"
TEMPLATE_DIR = REPO_ROOT / "helm" / "dpf-hcp-provisioner-operator" / "templates"

GENERATED_MARKER = "{{/* Generated by sync-helm-rbac.py — do not edit. */}}\n"

HELM_NAME = '{{ include "dpf-hcp-provisioner-operator.fullname" . }}-manager-role'
HELM_LABELS = (
    "\n" '    {{- include "dpf-hcp-provisioner-operator.labels" . | nindent 4 }}'
)


def load_docs():
    result = subprocess.run(
        ["yq", "-o", "json", "eval-all", "[.]", str(SOURCE)],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def render_doc(doc_index):
    expr = (
        f"select(document_index == {doc_index})"
        ' | .metadata.name = "__HELM_NAME__"'
        ' | .metadata.labels = "__HELM_LABELS__"'
    )
    result = subprocess.run(
        ["yq", "-I", "2", expr, str(SOURCE)],
        capture_output=True,
        text=True,
        check=True,
    )
    text = result.stdout.lstrip("-\n ")
    for placeholder, value in [("__HELM_NAME__", HELM_NAME), ("__HELM_LABELS__", HELM_LABELS)]:
        text = text.replace(f"'{placeholder}'", value).replace(placeholder, value)
    return text


def template_filename(doc):
    namespace = doc.get("metadata", {}).get("namespace", "")
    parts = (
        [doc["kind"].lower()]
        + ([namespace] if namespace else [])
        + [doc["metadata"]["name"]]
    )
    return f"{'-'.join(parts)}.yaml"


def main():
    if not SOURCE.exists():
        print(
            f"Error: {SOURCE} not found. Run 'make manifests' first.", file=sys.stderr
        )
        sys.exit(1)

    for f in TEMPLATE_DIR.iterdir():
        if f.is_file() and f.read_text().startswith(GENERATED_MARKER):
            f.unlink()

    docs = load_docs()

    for i, doc in enumerate(docs):
        target = TEMPLATE_DIR / template_filename(doc)
        target.write_text(GENERATED_MARKER + render_doc(i))


if __name__ == "__main__":
    main()
