//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFHCPProvisioner) DeepCopyInto(out *DPFHCPProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFHCPProvisioner.
func (in *DPFHCPProvisioner) DeepCopy() *DPFHCPProvisioner {
	if in == nil {
		return nil
	}
	out := new(DPFHCPProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPFHCPProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFHCPProvisionerList) DeepCopyInto(out *DPFHCPProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPFHCPProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFHCPProvisionerList.
func (in *DPFHCPProvisionerList) DeepCopy() *DPFHCPProvisionerList {
	if in == nil {
		return nil
	}
	out := new(DPFHCPProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPFHCPProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFHCPProvisionerSpec) DeepCopyInto(out *DPFHCPProvisionerSpec) {
	*out = *in
	out.DPUClusterRef = in.DPUClusterRef
	out.SSHKeySecretRef = in.SSHKeySecretRef
	out.PullSecretRef = in.PullSecretRef
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFHCPProvisionerSpec.
func (in *DPFHCPProvisionerSpec) DeepCopy() *DPFHCPProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(DPFHCPProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFHCPProvisionerStatus) DeepCopyInto(out *DPFHCPProvisionerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostedClusterRef != nil {
		in, out := &in.HostedClusterRef, &out.HostedClusterRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.KubeConfigSecretRef != nil {
		in, out := &in.KubeConfigSecretRef, &out.KubeConfigSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFHCPProvisionerStatus.
func (in *DPFHCPProvisionerStatus) DeepCopy() *DPFHCPProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(DPFHCPProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUClusterReference) DeepCopyInto(out *DPUClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUClusterReference.
func (in *DPUClusterReference) DeepCopy() *DPUClusterReference {
	if in == nil {
		return nil
	}
	out := new(DPUClusterReference)
	in.DeepCopyInto(out)
	return out
}
