# Default values for dpu-worker-config

# Override the chart name used in app.kubernetes.io/name labels
nameOverride: ""

# Override the full name used in resource names
fullnameOverride: ""

# Additional labels to apply to all resources
commonLabels: {}

# Additional annotations to apply to all resources
commonAnnotations: {}
